# Generated by Django 4.2.9 on 2025-11-03 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lers', '0006_alter_lersmessage_encrypted_content_and_more'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetimeline',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lers.lersrequest'),
        ),
    ]
