# Generated by Django 4.2.9 on 2025-10-17 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('evidence', '0001_initial'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LERSRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('request_type', models.CharField(choices=[('BANK_TX_HISTORY', 'Bank Transaction History'), ('BANK_ACCOUNT_DETAILS', 'Bank Account Details'), ('CDR', 'Call Detail Records (CDR)'), ('SIM_DETAILS', 'SIM Card Details'), ('UPI_TX', 'UPI Transaction History'), ('WALLET_DETAILS', 'Wallet Details'), ('ECOMMERCE_ORDER', 'E-commerce Order Details'), ('SOCIAL_PROFILE', 'Social Media Profile'), ('IP_LOGS', 'IP Access Logs'), ('DEVICE_INFO', 'Device Information'), ('KYC_DOCUMENTS', 'KYC Documents'), ('OTHER', 'Other')], max_length=30)),
                ('provider', models.CharField(max_length=255)),
                ('identifiers', models.JSONField(default=dict)),
                ('description', models.TextField()),
                ('date_range_from', models.DateField(blank=True, null=True)),
                ('date_range_to', models.DateField(blank=True, null=True)),
                ('legal_mandate_type', models.CharField(max_length=50)),
                ('court_order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('SUBMITTED', 'Submitted to Company'), ('ACKNOWLEDGED', 'Acknowledged by Company'), ('IN_PROGRESS', 'In Progress'), ('RESPONSE_UPLOADED', 'Response Uploaded'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10)),
                ('sla_due_date', models.DateTimeField(blank=True, null=True)),
                ('sla_breached', models.BooleanField(default=False)),
                ('sla_breach_notified', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lers_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lers_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lers_requests', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lers_requests_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('legal_mandate_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lers_legal_mandates', to='evidence.evidencefile')),
                ('provider_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lers_requests_received', to='tenants.tenant')),
            ],
            options={
                'db_table': 'lers_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LERSApprovalWorkflow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('REQUEST_CHANGES', 'Request Changes')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('signature_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('action_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lers_approvals', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow', to='lers.lersrequest')),
            ],
            options={
                'db_table': 'lers_approval_workflow',
                'ordering': ['-action_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LERSTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('request_type', models.CharField(choices=[('BANK_TX_HISTORY', 'Bank Transaction History'), ('BANK_ACCOUNT_DETAILS', 'Bank Account Details'), ('CDR', 'Call Detail Records (CDR)'), ('SIM_DETAILS', 'SIM Card Details'), ('UPI_TX', 'UPI Transaction History'), ('WALLET_DETAILS', 'Wallet Details'), ('ECOMMERCE_ORDER', 'E-commerce Order Details'), ('SOCIAL_PROFILE', 'Social Media Profile'), ('IP_LOGS', 'IP Access Logs'), ('DEVICE_INFO', 'Device Information'), ('KYC_DOCUMENTS', 'KYC Documents'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('template_fields', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lers_templates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'lers_templates',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['request_type', 'is_active'], name='lers_templa_request_5c121d_idx')],
            },
        ),
        migrations.CreateModel(
            name='LERSResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('response_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('PARSED', 'Parsed'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=20)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('signature', models.TextField(blank=True, null=True)),
                ('signature_verified', models.BooleanField(default=False)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='lers.lersrequest')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lers_responses_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lers_responses',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['request', '-submitted_at'], name='lers_respon_request_68682f_idx'), models.Index(fields=['status'], name='lers_respon_status_42bc86_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lersrequest',
            index=models.Index(fields=['request_number'], name='lers_reques_request_92e564_idx'),
        ),
        migrations.AddIndex(
            model_name='lersrequest',
            index=models.Index(fields=['case', 'status'], name='lers_reques_case_id_1f707b_idx'),
        ),
        migrations.AddIndex(
            model_name='lersrequest',
            index=models.Index(fields=['provider_tenant', 'status'], name='lers_reques_provide_ef8776_idx'),
        ),
        migrations.AddIndex(
            model_name='lersrequest',
            index=models.Index(fields=['status', 'sla_due_date'], name='lers_reques_status_ddd01e_idx'),
        ),
        migrations.AddIndex(
            model_name='lersrequest',
            index=models.Index(fields=['-created_at'], name='lers_reques_created_63582a_idx'),
        ),
        migrations.AddIndex(
            model_name='lersapprovalworkflow',
            index=models.Index(fields=['request', '-action_timestamp'], name='lers_approv_request_df8d59_idx'),
        ),
    ]
