# Generated by Django 4.2.9 on 2025-10-22 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('user', models.OneToOneField(help_text='User this presence belongs to', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='presence', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('AWAY', 'Away'), ('OFFLINE', 'Offline')], default='OFFLINE', help_text='Current online status', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Last activity timestamp (auto-updated)')),
                ('last_online', models.DateTimeField(blank=True, help_text='Last time user was online', null=True)),
                ('socket_id', models.CharField(blank=True, help_text='Current WebSocket connection ID', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (device, browser, etc.)')),
            ],
            options={
                'verbose_name_plural': 'User Presences',
            },
        ),
        migrations.CreateModel(
            name='LERSNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('NEW_MESSAGE', 'New Message'), ('RESPONSE_RECEIVED', 'Response Received'), ('APPROVAL_NEEDED', 'Approval Needed'), ('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_REJECTED', 'Request Rejected'), ('CHANGES_REQUESTED', 'Changes Requested'), ('DEADLINE_APPROACHING', 'Deadline Approaching'), ('REQUEST_OVERDUE', 'Request Overdue'), ('REQUEST_SUBMITTED', 'Request Submitted'), ('PROVIDER_ACKNOWLEDGED', 'Provider Acknowledged')], help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification message body')),
                ('icon', models.CharField(blank=True, help_text='Icon name for UI (e.g., "bell", "check", "alert")', max_length=50)),
                ('link', models.CharField(blank=True, help_text='Deep link URL to navigate to (e.g., /lers/requests/123)', max_length=255)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', help_text='Notification priority level', max_length=20)),
                ('read', models.BooleanField(db_index=True, default=False, help_text='Whether user has read this notification')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was read', null=True)),
                ('delivered', models.BooleanField(default=False, help_text='Whether notification was delivered via WebSocket')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was delivered', null=True)),
                ('email_sent', models.BooleanField(default=False, help_text='Whether email notification was sent (for high priority)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (action buttons, data for rendering, etc.)')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, help_text='LERS request this notification is about', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='lers.lersrequest')),
                ('user', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='lers_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read', 'created_at'], name='lers_lersno_user_id_b5466f_idx'), models.Index(fields=['user', '-created_at'], name='lers_lersno_user_id_877405_idx'), models.Index(fields=['request', 'created_at'], name='lers_lersno_request_52e2a9_idx'), models.Index(fields=['priority', 'read'], name='lers_lersno_priorit_ebc173_idx')],
            },
        ),
        migrations.CreateModel(
            name='LERSMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sender_type', models.CharField(choices=[('IO', 'Investigating Officer'), ('PROVIDER', 'Data Provider'), ('SYSTEM', 'System Generated')], help_text='Type of sender (IO, Provider, or System)', max_length=20)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text Message'), ('FILE', 'File Attachment'), ('SYSTEM', 'System Message')], default='TEXT', help_text='Type of message', max_length=20)),
                ('message_text', models.TextField(help_text='Message content')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='Array of file URLs: [{url, filename, size, type}]')),
                ('read_by_receiver', models.BooleanField(db_index=True, default=False, help_text='Whether the recipient has read this message')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when message was read', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (typing indicators, reactions, etc.)')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(help_text='LERS request this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='lers.lersrequest')),
                ('sender', models.ForeignKey(help_text='User who sent this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lers_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['request', 'created_at'], name='lers_lersme_request_3a6738_idx'), models.Index(fields=['sender', 'created_at'], name='lers_lersme_sender__4e9dbd_idx'), models.Index(fields=['read_by_receiver'], name='lers_lersme_read_by_2f9137_idx')],
            },
        ),
    ]
