# Generated by Django 4.2.9 on 2025-11-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),  # STANDALONE: Changed from 0005
        ('lers', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lersrequest',
            name='idx_lers_sla_deadline',
        ),
        migrations.RemoveIndex(
            model_name='lersrequest',
            name='idx_lers_case_provider_status',
        ),
        migrations.RemoveIndex(
            model_name='lersrequest',
            name='idx_lers_creator_status_date',
        ),
        migrations.RemoveIndex(
            model_name='lersrequest',
            name='idx_lers_provider_sla',
        ),
        migrations.RemoveIndex(
            model_name='lersrequest',
            name='idx_lers_status_priority_date',
        ),
        migrations.AlterField(
            model_name='lersrequest',
            name='case',
            field=models.ForeignKey(blank=True, help_text='Optional case link. Leave empty for standalone LERS requests.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lers_requests', to='cases.case'),
        ),
    ]
