# Generated by Django 4.2.9 on 2025-11-01 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('lers', '0005_add_e2e_encryption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lersmessage',
            name='encrypted_content',
            field=models.TextField(blank=True, help_text='Encrypted message content (base64 encoded ciphertext)', null=True),
        ),
        migrations.AlterField(
            model_name='lersmessage',
            name='encrypted_key',
            field=models.TextField(blank=True, help_text='Encrypted symmetric key for decrypting message (RSA encrypted, base64 encoded)', null=True),
        ),
        migrations.AlterField(
            model_name='lersmessage',
            name='message_text',
            field=models.TextField(help_text='Message content (plain text for non-encrypted messages)'),
        ),
        migrations.CreateModel(
            name='ProviderServiceProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('service_hours', models.CharField(default='Monday-Friday, 9:00 AM - 6:00 PM', help_text='When the provider processes LERS requests', max_length=200)),
                ('holidays_affect_sla', models.BooleanField(default=True, help_text='Whether public holidays extend SLA deadlines')),
                ('nodal_officer_name', models.CharField(max_length=200)),
                ('nodal_officer_designation', models.CharField(max_length=100)),
                ('nodal_officer_email', models.EmailField(max_length=254)),
                ('nodal_officer_phone', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact for urgent/critical requests', max_length=100)),
                ('overall_sla_compliance_rate', models.FloatField(blank=True, help_text='Overall SLA compliance across all data types', null=True)),
                ('total_requests_received', models.IntegerField(default=0)),
                ('total_requests_completed', models.IntegerField(default=0)),
                ('avg_response_time_hours', models.FloatField(blank=True, help_text='Average response time across all requests', null=True)),
                ('rejection_rate', models.FloatField(blank=True, help_text='Percentage of requests rejected due to incomplete information', null=True)),
                ('clarification_request_rate', models.FloatField(blank=True, help_text='Percentage of requests requiring clarification', null=True)),
                ('iso_certified', models.BooleanField(default=False)),
                ('iso_certificate_number', models.CharField(blank=True, max_length=100)),
                ('data_security_certified', models.BooleanField(default=False)),
                ('govt_empaneled', models.BooleanField(default=False)),
                ('service_commitment', models.TextField(blank=True, help_text='Public commitment statement to law enforcement')),
                ('metrics_last_updated', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('provider_tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_profile', to='tenants.tenant')),
            ],
            options={
                'db_table': 'lers_provider_service_profile',
            },
        ),
        migrations.CreateModel(
            name='ProviderDataCatalog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='E.g., "Account Statement (6 months)", "CDR - Incoming/Outgoing"', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what data is included')),
                ('category', models.CharField(choices=[('BANKING', 'Banking & Financial Records'), ('TELECOM', 'Telecom & CDR'), ('PAYMENT', 'Payment & UPI Transactions'), ('IDENTITY', 'KYC & Identity Documents'), ('CREDIT', 'Credit Card & Loan Records'), ('LOCATION', 'Location & Tower Data'), ('DEVICE', 'Device & IMEI Information'), ('ECOMMERCE', 'E-commerce Orders & Delivery'), ('SOCIAL', 'Social Media Records'), ('OTHER', 'Other Data Types')], db_index=True, max_length=20)),
                ('sla_turnaround_hours', models.IntegerField(help_text='Committed turnaround time in hours (e.g., 48 for 2 days)')),
                ('sla_business_hours_only', models.BooleanField(default=True, help_text='If true, SLA counts only business hours (Mon-Fri 9AM-6PM)')),
                ('actual_avg_turnaround_hours', models.FloatField(blank=True, help_text='Actual average turnaround based on historical data', null=True)),
                ('actual_median_turnaround_hours', models.FloatField(blank=True, help_text='Median turnaround (more accurate than average)', null=True)),
                ('sla_compliance_rate', models.FloatField(blank=True, help_text='Percentage of requests delivered within SLA (e.g., 92.5)', null=True)),
                ('total_requests_fulfilled', models.IntegerField(default=0, help_text='Total number of requests fulfilled for this data type')),
                ('required_fields', models.JSONField(default=list, help_text='\n        List of fields required from law enforcement.\n        Example:\n        [\n            {\n                "field": "account_number",\n                "label": "Account Number",\n                "type": "text",\n                "required": true,\n                "placeholder": "Enter 16-digit account number",\n                "validation": "^[0-9]{16}$",\n                "help_text": "16-digit account number as printed on passbook"\n            },\n            {\n                "field": "date_from",\n                "label": "From Date",\n                "type": "date",\n                "required": true,\n                "max_range_days": 180,\n                "help_text": "Maximum 6 months of history per request"\n            }\n        ]\n        ')),
                ('required_legal_mandate', models.CharField(help_text='E.g., "Section 91 CrPC" or "Section 91 CrPC + Court Order"', max_length=200)),
                ('requires_court_order', models.BooleanField(default=False)),
                ('requires_pan_verification', models.BooleanField(default=False)),
                ('additional_requirements', models.TextField(blank=True, help_text='Any additional legal/procedural requirements')),
                ('output_format', models.CharField(choices=[('PDF', 'PDF Document'), ('EXCEL', 'Excel Spreadsheet'), ('CSV', 'CSV File'), ('JSON', 'JSON Data'), ('SCANNED_PDF', 'Scanned PDF (Images)'), ('MIXED', 'Multiple Formats')], max_length=20)),
                ('output_description', models.TextField(blank=True, help_text='Description of what the output will contain')),
                ('sample_output_file', models.FileField(blank=True, help_text='Redacted sample output for reference', null=True, upload_to='catalog_samples/')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this catalog item is currently available')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured items shown prominently')),
                ('notes_for_law_enforcement', models.TextField(blank=True, help_text='Important notes or tips for requesting this data')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for provider staff (not visible to law enforcement)')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('provider_tenant', models.ForeignKey(help_text='The provider (bank/telco) offering this data', on_delete=django.db.models.deletion.CASCADE, related_name='data_catalog_items', to='tenants.tenant')),
            ],
            options={
                'db_table': 'lers_provider_data_catalog',
                'ordering': ['provider_tenant', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogUsageAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('requests_received', models.IntegerField(default=0)),
                ('requests_completed', models.IntegerField(default=0)),
                ('requests_rejected', models.IntegerField(default=0)),
                ('avg_turnaround_hours', models.FloatField(blank=True, null=True)),
                ('sla_met_count', models.IntegerField(default=0)),
                ('sla_missed_count', models.IntegerField(default=0)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_analytics', to='lers.providerdatacatalog')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lers_catalog_usage_analytics',
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddField(
            model_name='lersrequest',
            name='catalog_item',
            field=models.ForeignKey(blank=True, help_text='Provider catalog item selected for this request (if using catalog)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='lers.providerdatacatalog'),
        ),
        migrations.AddIndex(
            model_name='providerdatacatalog',
            index=models.Index(fields=['provider_tenant', 'category'], name='lers_provid_provide_29c8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='providerdatacatalog',
            index=models.Index(fields=['is_active'], name='lers_provid_is_acti_f364dd_idx'),
        ),
        migrations.AddIndex(
            model_name='providerdatacatalog',
            index=models.Index(fields=['sla_turnaround_hours'], name='lers_provid_sla_tur_f712cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='providerdatacatalog',
            unique_together={('provider_tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='catalogusageanalytics',
            unique_together={('catalog_item', 'period_start', 'period_end')},
        ),
    ]
