"""
Celery tasks for evidence processing.
"""
from celery import shared_task
import logging
import json
import zipfile
from io import BytesIO
from datetime import datetime
import hashlib

logger = logging.getLogger(__name__)


@shared_task(bind=True)
def generate_court_bundle(self, bundle_id):
    """
    Generate court bundle with evidence files and signed manifest.
    
    Args:
        bundle_id (str): CourtBundle ID
    """
    from .models import CourtBundle, ChainOfCustody
    from .storage import get_evidence_vault
    
    try:
        bundle = CourtBundle.objects.get(id=bundle_id)
        bundle.status = 'GENERATING'
        bundle.save(update_fields=['status'])
        
        logger.info(f"Generating court bundle: {bundle_id}")
        
        # Create ZIP file in memory
        zip_buffer = BytesIO()
        
        with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
            manifest_data = {
                'bundle_name': bundle.bundle_name,
                'case_number': bundle.case.case_number,
                'generated_at': datetime.now().isoformat(),
                'generated_by': bundle.created_by.full_name if bundle.created_by else 'System',
                'court_name': bundle.court_name,
                'case_reference': bundle.case_reference,
                'evidence_files': []
            }
            
            # Add each evidence file
            for evidence in bundle.evidence_files.all():
                try:
                    # Download evidence file
                    file_content = get_evidence_vault().download_evidence(
                        storage_path=evidence.storage_path,
                        decrypt=True
                    )
                    
                    # Add to ZIP
                    zip_file.writestr(evidence.file_name, file_content)
                    
                    # Add to manifest
                    manifest_data['evidence_files'].append({
                        'file_name': evidence.file_name,
                        'sha256': evidence.sha256_hash,
                        'file_size': evidence.file_size,
                        'uploaded_by': evidence.uploaded_by.full_name if evidence.uploaded_by else 'Unknown',
                        'uploaded_at': evidence.created_at.isoformat(),
                        'description': evidence.description,
                        'custody_records': [
                            {
                                'action': record.action,
                                'actor': record.actor.full_name if record.actor else 'System',
                                'timestamp': record.action_timestamp.isoformat(),
                                'integrity_verified': record.integrity_verified
                            }
                            for record in evidence.custody_records.all()
                        ]
                    })
                    
                    logger.info(f"Added evidence to bundle: {evidence.file_name}")
                    
                except Exception as e:
                    logger.error(f"Failed to add evidence {evidence.id} to bundle: {str(e)}")
                    continue
            
            # Add manifest to ZIP
            manifest_json = json.dumps(manifest_data, indent=2)
            zip_file.writestr('MANIFEST.json', manifest_json)
            
            # Add README
            readme_content = f"""
COURT BUNDLE - {bundle.bundle_name}
=====================================

Case Number: {bundle.case.case_number}
Generated: {datetime.now().isoformat()}
Generated By: {bundle.created_by.full_name if bundle.created_by else 'System'}

Court Information:
- Court Name: {bundle.court_name or 'N/A'}
- Case Reference: {bundle.case_reference or 'N/A'}

Evidence Files: {len(manifest_data['evidence_files'])}

This bundle contains digital evidence collected for the above case.
All files have been verified for integrity and include chain-of-custody records.

Please refer to MANIFEST.json for detailed file information and custody chain.
"""
            zip_file.writestr('README.txt', readme_content)
        
        # Get ZIP content
        zip_content = zip_buffer.getvalue()
        bundle_size = len(zip_content)
        
        # Calculate bundle hash
        bundle_hash = hashlib.sha256(zip_content).hexdigest()
        
        # Upload bundle to storage
        bundle_path = f"cases/{bundle.case.id}/court_bundles/{bundle_id}.zip"
        
        from minio import Minio
        from django.conf import settings
        
        client = Minio(
            settings.MINIO_ENDPOINT,
            access_key=settings.MINIO_ACCESS_KEY,
            secret_key=settings.MINIO_SECRET_KEY,
            secure=settings.MINIO_SECURE
        )
        
        client.put_object(
            bucket_name=settings.MINIO_BUCKET_NAME,
            object_name=bundle_path,
            data=BytesIO(zip_content),
            length=bundle_size,
            content_type='application/zip'
        )
        
        # Sign manifest (simplified - in production use proper digital signature)
        from cryptography.hazmat.primitives import hashes
        from cryptography.hazmat.backends import default_backend
        manifest_signature = hashlib.sha256(manifest_json.encode()).hexdigest()
        
        # Update bundle
        bundle.status = 'READY'
        bundle.bundle_path = bundle_path
        bundle.bundle_size = bundle_size
        bundle.bundle_hash = bundle_hash
        bundle.manifest = manifest_data
        bundle.manifest_signature = manifest_signature
        bundle.generated_at = datetime.now()
        bundle.save()
        
        logger.info(f"Court bundle generated successfully: {bundle_id}")
        
        return {
            'success': True,
            'bundle_id': bundle_id,
            'bundle_size': bundle_size,
            'file_count': len(manifest_data['evidence_files'])
        }
        
    except Exception as e:
        logger.error(f"Failed to generate court bundle {bundle_id}: {str(e)}")
        
        try:
            bundle = CourtBundle.objects.get(id=bundle_id)
            bundle.status = 'FAILED'
            bundle.save(update_fields=['status'])
        except:
            pass
        
        return {'success': False, 'error': str(e)}


@shared_task
def parse_evidence_file(evidence_id):
    """
    Send evidence file to parser service for processing.
    
    Args:
        evidence_id (str): EvidenceFile ID
    """
    from .models import EvidenceFile
    from .storage import get_evidence_vault
    import requests
    from django.conf import settings
    
    try:
        evidence = EvidenceFile.objects.get(id=evidence_id)
        
        logger.info(f"Parsing evidence: {evidence.file_name}")
        
        # Download file
        file_content = get_evidence_vault().download_evidence(
            storage_path=evidence.storage_path,
            decrypt=True
        )
        
        # Send to parser service
        parser_url = f"{settings.PARSER_SERVICE_URL}/parse"
        
        files = {'file': (evidence.file_name, file_content, evidence.mime_type)}
        data = {
            'file_type': evidence.file_type,
            'evidence_id': str(evidence.id)
        }
        
        response = requests.post(parser_url, files=files, data=data, timeout=300)
        
        if response.status_code == 200:
            parser_result = response.json()
            
            evidence.parsed = True
            evidence.parser_version = parser_result.get('parser_version')
            evidence.parser_output = parser_result.get('output')
            evidence.parser_confidence = parser_result.get('confidence', 1.0)
            evidence.save()
            
            logger.info(f"Evidence parsed successfully: {evidence_id}")
            
            return {'success': True, 'evidence_id': evidence_id}
        else:
            logger.error(f"Parser service error: {response.status_code}")
            return {'success': False, 'error': f'Parser service returned {response.status_code}'}
            
    except Exception as e:
        logger.error(f"Failed to parse evidence {evidence_id}: {str(e)}")
        return {'success': False, 'error': str(e)}

