# Generated by Django 4.2.9 on 2025-11-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_enhanced_audit_logging'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_action_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_ip_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_status_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_risk_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_time_action_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='device_fingerprint',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='duration_ms',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='geolocation',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='request_method',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='request_path',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='request_query',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='response_status',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='tags',
        ),
    ]
