# Generated by Django 4.2.9 on 2025-11-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_encryption_keys'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apikey',
            name='idx_apikey_user_active',
        ),
        migrations.RemoveIndex(
            model_name='loginhistory',
            name='idx_login_success_date',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_user_tenant_role_active',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_user_employee_id',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_user_active_login',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_user_tenant_active_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mfa_backup_codes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mfa_last_verified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mfa_setup_at',
        ),
    ]
