# Generated by Django 4.2.9 on 2025-10-17 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainOfCustody',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VIEWED', 'Viewed'), ('DOWNLOADED', 'Downloaded'), ('EDITED', 'Edited'), ('SHARED', 'Shared'), ('VERIFIED', 'Integrity Verified'), ('EXPORTED', 'Exported to Bundle')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('file_hash_at_action', models.CharField(blank=True, max_length=64, null=True)),
                ('integrity_verified', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('action_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'chain_of_custody',
                'ordering': ['-action_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CourtBundle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bundle_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('bundle_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('bundle_size', models.BigIntegerField(blank=True, null=True)),
                ('bundle_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('manifest_signature', models.TextField(blank=True, null=True)),
                ('court_name', models.CharField(blank=True, max_length=255, null=True)),
                ('case_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'court_bundles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_tags', to='tenants.tenant')),
            ],
            options={
                'db_table': 'evidence_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('DOCUMENT', 'Document (PDF/DOC)'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('SPREADSHEET', 'Spreadsheet'), ('ARCHIVE', 'Archive (ZIP/RAR)'), ('OTHER', 'Other')], max_length=20)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('storage_path', models.CharField(max_length=1000)),
                ('encrypted_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('sha256_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('md5_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('source', models.CharField(choices=[('MANUAL_UPLOAD', 'Manual Upload'), ('LERS_RESPONSE', 'LERS Response'), ('PARSER_OUTPUT', 'Parser Output'), ('SYSTEM_GENERATED', 'System Generated')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('parsed', models.BooleanField(default=False)),
                ('parser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('parser_output', models.JSONField(blank=True, default=dict, null=True)),
                ('parser_confidence', models.FloatField(blank=True, null=True)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('encryption_algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('encryption_key_id', models.CharField(blank=True, max_length=100, null=True)),
                ('legal_hold', models.BooleanField(default=False)),
                ('retention_until', models.DateField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='cases.case')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidence_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
