# Generated by Django 4.2.9 on 2025-10-17 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evidence', '0001_initial'),
        ('lers', '0001_initial'),
        ('cases', '0001_initial'),  # STANDALONE: Changed from 0002_initial
    ]

    operations = [
        migrations.AddField(
            model_name='evidencefile',
            name='lers_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_files', to='lers.lersresponse'),
        ),
        migrations.AddField(
            model_name='evidencefile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courtbundle',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_bundles', to='cases.case'),
        ),
        migrations.AddField(
            model_name='courtbundle',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_bundles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courtbundle',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courtbundle',
            name='evidence_files',
            field=models.ManyToManyField(related_name='court_bundles', to='evidence.evidencefile'),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chainofcustody',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_records', to='evidence.evidencefile'),
        ),
        migrations.AlterUniqueTogether(
            name='evidencetag',
            unique_together={('name', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='evidencefile',
            index=models.Index(fields=['case', '-created_at'], name='evidence_fi_case_id_c322d6_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencefile',
            index=models.Index(fields=['sha256_hash'], name='evidence_fi_sha256__bb2a68_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencefile',
            index=models.Index(fields=['file_type'], name='evidence_fi_file_ty_f4e834_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencefile',
            index=models.Index(fields=['source'], name='evidence_fi_source_77f6eb_idx'),
        ),
        migrations.AddIndex(
            model_name='courtbundle',
            index=models.Index(fields=['case', '-created_at'], name='court_bundl_case_id_4d4162_idx'),
        ),
        migrations.AddIndex(
            model_name='courtbundle',
            index=models.Index(fields=['status'], name='court_bundl_status_193f19_idx'),
        ),
        migrations.AddIndex(
            model_name='chainofcustody',
            index=models.Index(fields=['evidence', '-action_timestamp'], name='chain_of_cu_evidenc_60de9e_idx'),
        ),
        migrations.AddIndex(
            model_name='chainofcustody',
            index=models.Index(fields=['actor'], name='chain_of_cu_actor_i_6ecb9e_idx'),
        ),
    ]
