# Generated by Django 4.2.9 on 2025-11-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='courtbundle',
            name='bundle_sig_verified_idx',
        ),
        migrations.RemoveIndex(
            model_name='evidencefile',
            name='evidence_sig_verified_idx',
        ),
        migrations.RemoveIndex(
            model_name='evidencefile',
            name='idx_evidence_case_type',
        ),
        migrations.RemoveIndex(
            model_name='evidencefile',
            name='idx_evidence_uploader_date',
        ),
        migrations.RemoveIndex(
            model_name='evidencefile',
            name='idx_evidence_legal_hold',
        ),
        migrations.RemoveIndex(
            model_name='evidencefile',
            name='idx_evidence_parsed_type',
        ),
        migrations.RemoveIndex(
            model_name='evidencefile',
            name='idx_evidence_case_source',
        ),
        migrations.RemoveField(
            model_name='courtbundle',
            name='signature_algorithm',
        ),
        migrations.RemoveField(
            model_name='courtbundle',
            name='signature_verified',
        ),
        migrations.RemoveField(
            model_name='courtbundle',
            name='signed_at',
        ),
        migrations.RemoveField(
            model_name='evidencefile',
            name='digital_signature',
        ),
        migrations.RemoveField(
            model_name='evidencefile',
            name='last_signature_check',
        ),
        migrations.RemoveField(
            model_name='evidencefile',
            name='signature_verified',
        ),
        migrations.AlterField(
            model_name='courtbundle',
            name='manifest_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
