# Generated by Django 4.2.9 on 2025-11-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0005_remove_courtbundle_bundle_sig_verified_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainofcustody',
            name='action',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VIEWED', 'Viewed'), ('DOWNLOADED', 'Downloaded'), ('DOWNLOAD_URL_GENERATED', 'Download URL Generated'), ('EDITED', 'Edited'), ('SHARED', 'Shared'), ('VERIFIED', 'Integrity Verified'), ('EXPORTED', 'Exported to Bundle')], max_length=30),
        ),
    ]
