# Generated by Django 4.2.9 on 2025-10-17 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('tenant_type', models.CharField(choices=[('POLICE_STATION', 'Police Station'), ('COMPANY', 'Company'), ('STATE_UNIT', 'State Unit'), ('NATIONAL_UNIT', 'National Unit')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('jurisdiction', models.JSONField(blank=True, default=dict)),
                ('company_type', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('default_sla_hours', models.IntegerField(default=72)),
                ('urgent_sla_hours', models.IntegerField(default=24)),
                ('evidence_retention_days', models.IntegerField(default=2555)),
                ('log_retention_days', models.IntegerField(default=2555)),
                ('features_enabled', models.JSONField(default=dict)),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notification_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('sla_alert_enabled', models.BooleanField(default=True)),
                ('lers_api_enabled', models.BooleanField(default=False)),
                ('lers_webhook_url', models.URLField(blank=True, null=True)),
                ('lers_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_rate_limit', models.IntegerField(default=1000)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Settings',
                'verbose_name_plural': 'Tenant Settings',
                'db_table': 'tenant_settings',
            },
        ),
        migrations.CreateModel(
            name='TenantRelationship',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('relation_type', models.CharField(choices=[('FEDERATION', 'Federation (Share Cases)'), ('PARTNER', 'Partner'), ('APPROVED_PROVIDER', 'Approved Data Provider')], max_length=30)),
                ('can_view_cases', models.BooleanField(default=False)),
                ('can_request_data', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_relationships', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('from_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='tenants.tenant')),
                ('to_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_relationships',
                'indexes': [models.Index(fields=['from_tenant', 'relation_type'], name='tenant_rela_from_te_e6fc05_idx')],
                'unique_together': {('from_tenant', 'to_tenant', 'relation_type')},
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['code'], name='tenants_code_fcfd1b_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['tenant_type', 'is_active'], name='tenants_tenant__947a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['state', 'district'], name='tenants_state_de762c_idx'),
        ),
    ]
